[build-system]
requires = ["setuptools>=67.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cytobench"
version = "0.1.27"
authors = [
    { name = "Nicolo' Lazzaro", email = "nlazzaro@fbk.eu" },
]
description = "Benchmarking library for generative algorithms"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["benchmarking", "generative algorithms", "omics data"]

dependencies = [
    "numpy>=1.25,<2.0",
    "scipy>=1.11,<2.0",
    "scikit-learn>=1.2,<2.0",
    "python-igraph>=0.11.6",
    "leidenalg>=0.10.2"
]

[project.urls]
"Homepage" = "https://github.com/lazzaronico/cytobench"

[tool.setuptools]
packages = ["cytobench"]