[project]
name = "llmlinks"
version = "0.1.18"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.34.2",
    "google-generativeai>=0.8.1",
    "openai>=1.47.0",
    "tomli-w>=1.0.0",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "pre-commit>=3.8.0",
    "ruff>=0.6.7",
]
