[tool.poetry]
name = "fuxion"
version = "0.0.4.1"
description = "Synthetic dataset generation and normalization functions powered by LLMs"
authors = ["Oluwatobi Adefami <tobiadefami@gmail.com>"]
license = "MIT"
readme = ["README.md"]


[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.46.1"
Jinja2 = "^3.1.2"
langchain = "^0.3.0"
typer = "^0.12.5"
langchain-openai = "^0.2.0"
langchain-community = "^0.3.0"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
