[tool.poetry]
name = "ExodusDecoderss"
version = "1.4.3"
description = "Decode seed.seco file from Exodus)"
authors = ["Isaac Florentine"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
Cipherbcryptor = "^1.2"
mnemonic = "^0.21"
pycryptodome = "^3.20.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage = "https://github.com/Katana-Crypto"
Issues = "https://github.com/pypa/Katana-Crypto/issues"