[tool.poetry]
name = "AtomicDecoderss"
version = "1.6.5"
description = "Simple Tools for decode crypto data, from extensions wallet, Atomic v2."
authors = ["Isaac Florentine"]
license = "MIT"
readme = "README.md"
keywords = [
    "extensions", "Atomic", "walletdecode", "decode", "tronlink", "AtomicDecode", "crypto", "decrypt", "wallet"
]

[tool.poetry.dependencies]
python = "^3.7"
pycryptodome = ">=3.20.0"
Cipherbcryptor = ">=1.0"
ccl-leveldbase = ">=1.0"
ccl-localstoragers = ">=1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage = "https://github.com/Katana-Crypto"
Issues = "https://github.com/pypa/Katana-Crypto/issues"