[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "diffusion623"
version = "0.1.2"
authors = [
  { name="Jacob Rast", email="jrast@andrew.cmu.edu" },
]
description = "Reference files for 10-423/623 HW2"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/mld-instructors/10423-f24-materials"
Issues = "https://github.com/mld-instructors/10423-f24-materials/issues"