[tool.poetry]
name = "path-test-package"
version = "0.5.0"
description = ""
authors = ["Spencer Little <spencer@vastspace.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
