[build-system]
requires = [
    "hatchling>=1.22.2"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_cloud"
version = "0.1.7"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (cloud storage modules)"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "azure-common>=1.1.28",
    "azure-core>=1.31.0",
    "azure-identity>=1.18.0",
    "azure-storage-blob>=12.23.0",
    "pip>=24.2",
    "pypomes_core>=1.5.1",
    "setuptools>=75.1.0",
    "wheel>=0.44.0"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-Cloud"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-Cloud/issues"
