# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MarkerCount"
version = "0.7.0"
description = "Cell-type identification toolkit for single-cell RNA-Seq experiments."
readme = "README.md"
authors = [{ name = "Seokhyun Yoon", email = "syoon@dku.edu" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
keywords = ["single-cell omics", "bioinformatics"]
dependencies = [
]
# requires-python = "<3.10"

[project.optional-dependencies]
dev = ["numpy", "pandas", "scipy", "scikit-learn", "scikit-network"]

[project.urls]
Homepage = "https://github.com/combio-dku/"
repository = "https://github.com/combio-dku/HiCAT"

[project.scripts]
realpython = "reader.__main__:main"
