[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "authbase"
version = "1.0.7"
authors = [
    { name="Mizuki Hikaru", email="mizuki@hikaru.org" },
]
description = "Bootstrap is to frontend as AuthBase is to backend. A boilerplate that provides email-only user auth and email functionality."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi[standard]",
    "smtp-emailer",
    "mistletoe",
    "sqlalchemy",
]

[project.urls]
Homepage = "https://github.com/mizuki-hikaru/authbase"
Issues = "https://github.com/mizuki-hikaru/authbase/issues"
