[tool.poetry]
name = "komoutils"
version = "0.0.233"
description = ""
authors = ["Makhosonke Morafo <makhosonke@komokun.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pendulum = "3.0.0"
pytest = "^8.1.1"
pymongo = "^4.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
