[tool.poetry]
name = "gcs-logger"
version = "0.1.0"
description = "Logging tool for GameChange Solar projects"
license = "MIT"
authors = ["GameChangeSolar Software Team <software@gamechangesolar.com>"]
maintainers = ["David Aviles <david.aviles@gamechangesolar.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
