[tool.poetry]
name = "quasar-client"
version = "0.1.21"
description = "Yurts Python Quasar Client"
authors = ["Yurts Technologies, Inc. <dev@yurts.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.26.0"
openai = "^1.12.0"
pydantic = "^2.6.1"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
